#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE}")" || exit

git pull origin master

run() {
	rsync --exclude-from .sync-ignore -avh --no-perms . ~
  # shellcheck source=/dev/null
	source ~/.bash_profile
}

if [ "$1" == "--force" ] || [ "$1" == "-f" ]; then
	run
else
	read -rp "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    run
  fi
fi

unset run
