#!/usr/bin/env bash
set -eo pipefail

if ! hash brew 2>/dev/null; then
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# These are pre-requisites for certain software
brew bundle --file="$HOME"/.init/Brewfile