#!/usr/bin/env bash

if [ "$1" == 'on' ]
then
  launchctl load ~/Library/LaunchAgents/com.oho.cntlm.daemon.plist
  export http_proxy=http://127.0.0.1:3128
  export https_proxy=$http_proxy
  apm config set http-proxy http://127.0.0.1:3128
  apm config set https-proxy http://127.0.0.1:3128
fi

if [ "$1" == 'off' ]
then
  launchctl unload ~/Library/LaunchAgents/com.oho.cntlm.daemon.plist
  unset http_proxy
  unset https_proxy
  apm config delete http-proxy
  apm config delete https-proxy
fi
