#!/usr/bin/env bash

if [ "$1" == 'shutdown' ]
then
  for VM in $(VBoxManage list runningvms | awk '{ print $2; }'); do VBoxManage controlvm "$VM" poweroff; done
fi

if [ "$1" == 'destroy' ]
then
  for VM in $(VBoxManage list runningvms | awk '{ print $2; }'); do VBoxManage controlvm "$VM" destroy; done
fi

if [ "$1" == 'reconfigure-fusion' ]
then
  sudo -v
  sudo vmnet-cli --configure
  sudo vmnet-cli --stop
  sudo vmnet-cli --start
fi
