#!/usr/bin/env bash

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
  # shellcheck disable=SC2034
	colorflag="-G"
fi

# Allow aliases to be sudo'd
alias sudo='sudo '

# Always use color output for `ls`
alias ls="command ls -G"

alias c='pygmentize -O style=monokai -f console256 -g'

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# OS X has no `md5sum`, so use `md5` as a fallback
type -t md5sum > /dev/null || alias md5sum="md5"

# GREP_OPTIONS are depreciated
alias grep="grep --color=auto"

# Use multiple SSH configurations
alias ssh='cat ~/.ssh/config* > ~/.ssh/compilation && ssh -F ~/.ssh/compilation'

# Display the path in seperate lines
alias path='echo -e ${PATH//:/\\n}'

# Confirm before overwriting
# -----------------------------------------------------------------------------
# I know it is bad practice to override the default commands, but this is for
# my own safety. If you really want the original "instakill" versions, you can
# use "command rm", "\rm", or "/bin/rm" inside your own commands, aliases, or
# shell functions. Note that separate scripts are not affected by the aliases
# defined here.
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'