#!/usr/bin/env bash

# Add ~/.bin
export PATH="$HOME/.bin:$PATH";

# Load ~/.paths, ~/.extra, ~/.bash_prompt, ~/.exports, ~/.aliases and ~/.functions
# ~/.extra can be used for settings you don’t want to commit
for file in ~/.{paths,extra,bash_prompt,exports,aliases,functions,aws_credentials}; do
  # shellcheck source=/dev/null
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null;
done;

# Add tab completion for many Bash commands
# shellcheck source=/dev/null
source "$(brew --prefix)/etc/bash_completion"

if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
    # shellcheck source=/dev/null
    source ~/.gnupg/.gpg-agent-info
    export GPG_AGENT_INFO
else
    eval "$(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)"
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh;

# Add tab completion for SSH hostnames based on ~/.ssh/config.work, ignoring wildcards
[ -e "$HOME/.ssh/config.work" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config.work | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh;
