#!/usr/bin/env bash
# brew
export PATH="$HOME/.homebrew/bin:$HOME/.homebrew/sbin:$PATH"

# gnu
# shellcheck disable=SC2155
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

# java
export JAVA_HOME
JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"

# VMWare Fusion CLI Tools
export PATH="/Applications/VMware\ Fusion.app/Contents/Library:$PATH"

# ChefDK
eval "$(chef shell-init bash)"

# Go
export GOPATH="$HOME/code/samdunne/go"
export GOROOT
GOROOT="$(brew --prefix go)/libexec"
export PATH="$GOPATH/bin:$GOROOT/bin:$PATH"
